# Generated by Django 3.1.7 on 2021-04-03 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guests_can_pause',
            new_name='guest_can_pause',
        ),
    ]
